### ISSUE TITLE
Add Edgehog in 5 Minutes Page

### ISSUE THREAD

**Issue by bettio** [edgehog-device-manager/edgehog#138]
Add simple steps for running it with docker-compose

**Comment by rbino** [comment]
This needs to be re-evaluated later because right now an Edgehog installation based on docker-compose would not be fully functional since:
- The user would need an existing Astarte instance, and a docker-compose instance would not work since it uses non-standard URLs
- All functionality based on triggers would not work since an external Astarte would not be able to reach a local Edgehog deployment

**Comment by rbino** [comment]
Closed by #319
