### ISSUE TITLE
Support for Azure Blob Storage

### ISSUE THREAD

**Issue by bettio** [edgehog-device-manager/edgehog#233]
Edgehog should have either integrated native support for Azure Blob Storage in addition to S3 APIs, or there should be a documented procedure about how to use it.

**Comment by rbino** [comment]
Sketch of what needs to be done:
- Add two Azure Blob storage modules which should be equivalent to the current storage modules for the two Upload behaviours which are currently used: [Base Images](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/base_images/bucket_storage.ex) and [SystemModelPicture](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/assets/system_model_picture.ex)
- Possibly, rename the existing modules so they better reflect that they map to S3 (e.g. `S3BucketStorage`, `S3SystemModelPicture`
- Move the configuration to choose the specific storage to runtime instead of compile time (i.e. use `Application.fetch_env!`, do it in the function instead of in a module attribute)
- Add some additional env variables + logic to determine if we want to use S3 or Azure in `runtime.exs`

**Comment by rbino** [comment]
@noaccOS #254 might be relevant here too
